version: '3'
networks:
  nestAuth-network:
volumes:
  nestAuth-mongo:
   driver: local
services:
  mongo:
   image: mongo:6.0.3-focal
   networks:
     - nestAuth-network
   volumes:
     - nestAuth-mongo:/data/db
   ports:
     - 27017:27017
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: root